{{
  config(
    materialized = 'table',
    )
}}


with data_standard as (

SELECT
  date,
  info_key,
  advertiser_id,
  advertiser_name,
  campaign_id,
  campaign_name,
  site_id,
  site_name,
  placement_id,
  placement_name,
  placement_size,
  placement_strategy,
  content_category,
  ad_id,
  ad_name,
  creative_id,
  creative_name,
  impressions_original,
  clicks_original,
  media_cost_original,
  rich_media_video_plays_original,
  rich_media_video_first_quartile_completes_original,
  rich_media_video_midpoints_original,
  rich_media_video_third_quartile_completes_original,
  rich_media_video_completions_original,
  active_view_viewable_impressions_original,
  active_view_measurable_impressions_original,
  active_view_eligible_impressions_original,
  impressions,
  clicks,
  media_cost,
  rich_media_video_plays,
  rich_media_video_first_quartile_completes,
  rich_media_video_midpoints,
  rich_media_video_third_quartile_completes,
  rich_media_video_completions,
  active_view_viewable_impressions,
  active_view_measurable_impressions,
  active_view_eligible_impressions,
  total_conversions,
  activity_view_through_conversions,
  activity_click_through_conversions,
  total_conversions_revenue,
  activity_view_through_revenue,
  activity_click_through_revenue
FROM
 {{ ref('src_standard_76') }}
), 

data_floodlight as (

SELECT
  date,
  info_key,
  client_id,
  campaign_id,
  campaign_name,
  advertiser_id,
  advertiser_name,
  site_id,
  site_name,
  placement_id,
  placement_name,
  placement_size,
  placement_strategy,
  content_category,
  ad_id,
  ad_name,
  creative_id,
  creative_name,
  creative_type,
  --click_throught_url,
  activity_group,
  activity_id,
  activity_name,
  activity_view_through_conversions_original,
  activity_click_through_conversions_original,
  total_conversions_revenue,
  activity_view_through_revenue,
  activity_click_through_revenue,
  media_cost,
  activity_view_through_conversions,
  activity_click_through_conversions,
from {{ ref('src_floodlight_76') }}
)

select 
  data_standard.info_key,
  data_standard.date,
  data_standard.advertiser_id,
  data_standard.advertiser_name,
  data_standard.campaign_id,
  data_standard.campaign_name,
  data_standard.site_id,
  data_standard.site_name,
  data_standard.placement_id,
  data_standard.placement_name,
  data_standard.placement_size,
  data_standard.placement_strategy,
  data_standard.content_category,
  data_standard.ad_id,
  data_standard.ad_name,
  data_standard.creative_id,
  data_standard.creative_name,
  data_standard.impressions_original,
  data_standard.clicks_original,
  data_standard.media_cost_original,
  data_standard.rich_media_video_plays_original,
  data_standard.rich_media_video_first_quartile_completes_original,
  data_standard.rich_media_video_midpoints_original,
  data_standard.rich_media_video_third_quartile_completes_original,
  data_standard.rich_media_video_completions_original,
  data_standard.active_view_viewable_impressions_original,
  data_standard.active_view_measurable_impressions_original,
  data_standard.active_view_eligible_impressions_original,
  data_standard.impressions,
  data_standard.clicks,
  data_standard.media_cost,
  data_standard.rich_media_video_plays,
  data_standard.rich_media_video_first_quartile_completes,
  data_standard.rich_media_video_midpoints,
  data_standard.rich_media_video_third_quartile_completes,
  data_standard.rich_media_video_completions,
  data_standard.active_view_viewable_impressions,
  data_standard.active_view_measurable_impressions,
  data_standard.active_view_eligible_impressions,
  data_standard.total_conversions,
 -- data_standard.activity_view_through_conversions,
 -- data_standard.activity_click_through_conversions,
  --data_standard.total_conversions_revenue,
  --data_standard.activity_view_through_revenue,
  --data_standard.activity_click_through_revenue,
  data_floodlight.activity_name,
  data_floodlight.activity_id,
  data_floodlight.activity_view_through_conversions_original,
  data_floodlight.activity_click_through_conversions_original,
  data_floodlight.total_conversions_revenue,
  data_floodlight.activity_view_through_revenue,
  data_floodlight.activity_click_through_revenue,
  --data_floodlight.activity_view_through_revenue,
  --data_floodlight.activity_click_through_revenue,
  data_floodlight.activity_view_through_conversions,
  data_floodlight.activity_click_through_conversions,
  from data_standard
  left join data_floodlight
  on data_standard.info_key = data_standard.info_key


  
  