  

  {{
    config(
      materialized = 'table'
      )
  }}

select
    info_key,
    date,
    advertiser_name,
    advertiser_name_bis,
    dict.final_advertiser_name,
    dict.id_media_manager,
    dict.id_nouveau,
    dict.nom_annonceur,
    dict.ministere_annonceur,
    campaign_name,
    campaign_id,
    campaign_date,
    campaign_category,
    campaign_levier,
    campaign_ministere,
    campaign_name_name,
    campaign_adazzle_number,
    site_id,
    site_name,
    placement_id,
    placement_name,
    placement_type,
    placement_objective,
    placement_byying_method,
    placement_regie,
    placement_audience,
    placement_ciblage,
    placement_format_name,
    placement_format_size,
    placement_device,
    creative_id,
    creative_name,
    creative_asset_type,
    creative_format_name,
    creative_format_size,
    creative_message_name,
    impressions,
    clicks,
    media_cost,
    rich_media_video_plays,
    rich_media_video_first_quartile_completes,
    rich_media_video_midpoints,
    rich_media_video_third_quartile_completes,
    rich_media_video_completions,
    active_view_viewable_impressions,
    active_view_measurable_impressions,
    active_view_eligible_impressions,
    con.data_source_type,
    activity_name,
    pv_arrivee,
    pv_arrivee_no_rep,
    pc_arrivee,
    pc_arrivee_no_rep,
    pv_micro,
    pv_micro_no_rep,
    pc_micro,
    pc_micro_no_rep,
    pv_lead,
    pv_lead_no_rep,
    pc_lead,
    pc_lead_no_rep    
    from {{ ref('prd_adform_consolidation') }} con
    left join {{ ref('prd_advertiser_dict') }} dict
    on con.advertiser_name = dict.advertiser
