version: 2
sources:
  - name: gae_data
    loader: BigQuery
    schema: bi_raw_data
    database: dash-project-376514
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: global_dato_data_gae
        tags: ['Datorama Data']
        meta:
          contains_pii: false
          owner : " Team BI"

  - name: mapping_tag
    loader: BigQuery
    schema: bi_sheets
    database: dash-project-376514
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: ademe_sheets
        tags: ['Datorama Data']
        meta:
          contains_pii: false
        
  - name: data_adform_2023
    loader: BigQuery
    schema: ixiov2
    database: france-iprospect-ixio-197411
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: standard_5550  
        tags: ['Ixio Data']
        meta:
          contains_pii: false
          owner : "Team BI"
      - name: floodlight_5550  
        tags: ['Ixio Data']
        meta:
          contains_pii: false
          owner : "Team BI"

  - name: gae_ds_data
    loader: BigQuery
    schema: bi_gae_ds_export
    database: dash-project-376514
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: gae_ds_export_*  
        tags: ['Search Ads 360 Data']
        meta:
          contains_pii: false
          owner : "Team BI"
      - name: gae_ds_floodlight_export_*  
        tags: ['Search Ads 360 Data']
        meta:
          contains_pii: false
          owner : "Team BI"          

  - name: template_cm
    loader: BigQuery
    schema: ixiov2
    database: france-iprospect-ixio-197411
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: standard_76  
        tags: ['Ixio Data']
        meta:
          contains_pii: false
          owner : "Team BI"
      - name: floodlight_76  
        tags: ['Ixio Data']
        meta:
          contains_pii: false
          owner : "Team BI"